spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservicesdemo?createDatabaseIfNotExist=true
    username: pragradb
    password: Vivek123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl




